x-lib: &lib
  platform: linux/amd64
  image: crystal-es:dev
  depends_on:
    - database
  env_file:
    - .env-dev
  volumes: &backend_volumes
    - ./:/

services:
  cmd:
    <<: *lib
    deploy:
      replicas: 0
    entrypoint: /bin/bash
    command: -c

  console:
    <<: *lib
    entrypoint: /bin/bash
    command: ""
    stdin_open: true
    tty: true

  database:
    build:
      context: .
      dockerfile: Dockerfile.postgres
      target: service
    env_file:
      - .env-dev
    restart: always
    ports:
      - 5432
    volumes:
      - ./storage/postgres/data:/var/lib/postgresql/data

volumes:
  pgdata:
