#
# BASE artifact
#
FROM --platform=linux/amd64 ubuntu:24.04 AS base

RUN apt-get update && apt-get install -y curl gnupg2 git

RUN curl -fsSL https://crystal-lang.org/install.sh | bash -s -- --channel=stable

#
# BUILDER artifact
#
FROM base AS builder

RUN mkdir -p /crystal-es/lib
WORKDIR /crystal-es/lib
COPY ./shard* /crystal-es/lib/

# RUN  crystal -v
RUN shards install

COPY ./ /crystal-es/lib

#
# SERVICE 
#
FROM builder AS service

ENV image_name=crystal-es

WORKDIR /crystal-es/lib
