#
# BASE artifact
#
FROM 84codes/crystal:1.14.0-ubuntu-24.04 AS base

#
# BUILDER artifact
#
FROM base AS builder

RUN mkdir -p /crystal-es/lib
WORKDIR /crystal-es/lib
COPY ./shard* /crystal-es/lib/

# RUN  crystal -v
RUN shards install

COPY ./ /crystal-es/lib

#
# SERVICE 
#
FROM builder AS service

ENV image_name=crystal-es

WORKDIR /crystal-es/lib
