module ES
  # Shared by Reactor and Projection, which answer the same question about
  # themselves — "which events do I consume?" — and differ only in the method
  # they declare handlers with: a Reactor defines typed `call` overloads, a
  # Projection typed `apply` overloads.
  #
  # A base class includes this module and names its handler method from the
  # `inherited` hook:
  #
  # ```
  # abstract class Reactor
  #   include ES::EventDeclaration
  #
  #   macro inherited
  #     macro finished
  #       define_handles?("call")
  #     end
  #   end
  # end
  # ```
  #
  # The hook stays in the base class because the method name is the one thing
  # that genuinely differs; everything derived from it lives here.
  module EventDeclaration
    # Fallback for a base class and for any subclass declaring no handlers at
    # all. Overridden per subclass by `define_handles?`.
    macro included
      def self.handles?(event_class : ::ES::Event.class) : Bool
        false
      end
    end

    # Generates `self.handles?` from the typed `{{handler_method}}` overloads
    # the surrounding type defines — whether hand-written or generated by a
    # macro such as `ES::ProjectionDSL#apply`, since both are real methods by
    # the time `macro finished` runs.
    #
    # A type overriding the `ES::Event` catch-all consumes everything and
    # reports `true` for any event.
    #
    # Call this from inside a `macro finished` block: a macro call carries no
    # `{% %}` tokens, so the body below needs no escaping despite expanding two
    # levels down.
    macro define_handles?(handler_method)
      def self.handles?(event_class : ::ES::Event.class) : Bool
        {% for m in @type.methods.select { |x| x.name.stringify == handler_method && x.args.size == 1 } %}
          {% r = m.args[0].restriction %}
          {% if r.nil? %}
            return true
          {% elsif r.resolve? && r.resolve? <= ::ES::Event %}
            {% if r.resolve? == ::ES::Event %}
              return true
            {% else %}
              return true if event_class <= {{ r }}
            {% end %}
          {% end %}
        {% end %}
        false
      end
    end
  end
end
